### ISSUE TITLE
코드 난이도 하향 건의

### ISSUE THREAD

**Issue by Kei-410** [Sungmo-OSS-Project/txt_game_prototype#22]
코드의 품질이 저하되더라도 코드 사용의 난이도를 낮출 수 있도록, 전반적인 수정이 필요하다 생각합니다.

**Comment by Halozhan** [comment]
제가 만든 예제 이벤트 클래스들과 구식 코드 혹은 예제 실행코드들이 그대로 방치되어 코드가 복잡하다고 생각했습니다.
예제 이벤트는 실제 구현될 게임과는 다르므로 지워질 예정입니다.
구식 코드는 정리할 예정입니다.
예제 실행코드는 각 파일의 맨 밑에 if __name__ == "__main__":로 시작하는 부분의 코드입니다.
또. 복잡한 것은 타입 힌팅. 즉 파이썬 어노테이션이라는 기능은 파이썬처럼 동적 자료형을 갖고 인터프리터 언어에서 지원하는 자료형의 힌팅. 즉 변수의 자료형 도움말입니다.
타입 힌팅의 자료형은 반드시 지켜져야 하는 것은 아니며, 개발도구. 즉 VS Code와 같은 도구에서 클래스의 변수와 메소드를 자동완성해주는 개발을 좀더 원활하게 도와줍니다. 어노테이션을 작성하지 않으면 우린 이것이 무슨 타입인지 다시 확인해봐야할 필요가 있고, 오류가 발생할 수도 있고, 효율이 떨어집니다.

정리하자면
타입 힌팅을 제외한 나머지는 정리하는 것이 좋겠다고 생각합니다.

**Comment by Halozhan** [comment]
![image](https://user-images.githubusercontent.com/25768818/237028495-9a981cd7-5f88-4192-8c11-49caf12d3748.png)
지나치게 많은 타입 힌팅도 복잡하게 보이므로 수정하겠습니다!

**Comment by Kei-410** [comment]
전반적인 수정을 제 브렌치에서 진행했습니다.
