### ISSUE TITLE
days 변수 카운팅방식 건의

### ISSUE THREAD

**Issue by Kei-410** [Sungmo-OSS-Project/txt_game_prototype#27]
단발성 이벤트(예: 돌부리에 걸려 넘어지고, 체력 1 감소)의 경우 하루를 다 소비할만한 이벤트는 아니라고 봅니다.
따라서 굵직한 이벤트(선택지, 스토리 등)를 진행하는 경우에만 days가 카운팅 되도록 하는 방식을 제안합니다.

**Comment by Halozhan** [comment]
#45 에서 부연 설명이 있으므로 이 이슈는 닫겠습니다.
