### ISSUE TITLE
앞으로 진행할 계획

### ISSUE THREAD

**Issue by Kei-410** [Sungmo-OSS-Project/txt_game_prototype#38]
1. 구현해야 하는 기능들 나열할 예정.
나열된 기능 중 자신이 할 수 있을 것 같은 기능 골라서 코맨트 남기기.
코맨트 남긴 기능은 브랜치 만들어서 구현

2. 이벤트 생성용 메뉴얼 작성 예정
이벤트 생성하는 데 필요한 클래스, 객체를 수월하게 사용할 수 있도록 메뉴얼 제공 예정.

**Comment by Halozhan** [comment]
https://github.com/orgs/Sungmo-OSS-Project/projects/1/views/1
계획표는 여기서 확인할 수 있습니다.

**Comment by Halozhan** [comment]
1. #50 의 내용에서 재반영이 되었습니다.
2. 메뉴얼 작업이 완료되었습니다.
이슈를 닫겠습니다.
