### ISSUE TITLE
계획을 진행하는 대 필요한 사항

### ISSUE THREAD

**Issue by Kei-410** [Sungmo-OSS-Project/txt_game_prototype#39]
1. 코드리딩 및 작성
- 기능을 구현하는 작업은 코드 리딩 및 작성 능력을 필요로 합니다.

2. 이벤트 기획
- 이벤트를 제작하는 데 있어 코딩능력보다 다양한 기획이 더욱 중요합니다.
적극적으로 이벤트 구상에 대한 제안을 해주세요

**Comment by Halozhan** [comment]
> 코드 리딩 및 작성 늘력을 

작성 능력
