### ISSUE TITLE
이벤트 발생 방식

### ISSUE THREAD

**Issue by Kei-410** [Sungmo-OSS-Project/txt_game_prototype#45]
현재 이벤트의 종류로서 건의된 것은 다음과 같습니다.
1. 단발성 이벤트
2. 선택지형 이벤트
3. 연속 선택지형 이벤트
4. 스토리 이벤트(1, 2, 3 중 어느것이든 될 수 있다고 생각합니다.)

days 카운팅의 경우 2, 3, 스토리 이벤트 중 2, 3에 해당하는 이벤트가 발생한 경우 카운팅 하는 방식을 제안합니다.

이벤트 발생 방식
기본 골자는 이벤트 목록에서 랜덤하게 가져오는 것으로 합니다.
1. 이벤트 레벨이 존재하므로, 레벨별로 이벤트를 나누고, n레벨의 이벤트가 특정 횟수 이상 반복되면
 다음부터  n + 1 레벨 이벤트 발생.
2. 스토리 이벤트는 타이밍을 고정(예시: 이벤트 몇 번 진행하면 발생)

발생한 이벤트를 해당 회차의 게임에서 영구적으로 제외할 지에 대한 논의도 필요합니다.

다른 이벤트 발생 방식에 대한 의견도 적극적으로 건의해주세요.

**Comment by Halozhan** [comment]
> days 카운팅의 경우 2, 3, 스토리 이벤트 중 2, 3에 해당하는 이벤트가 발생한 경우 카운팅 하는 방식을 제안합니다.

#27 와 중복의 내용입니다.
