### ISSUE TITLE
아이템 목록의 타입에 관한 문제

### ISSUE THREAD

**Issue by Halozhan** [Sungmo-OSS-Project/txt_game_prototype#60]
![image](https://github.com/Sungmo-OSS-Project/txt_game_prototype/assets/25768818/1379edd2-902f-4c1a-ad02-c658edb81836)

1. 왼쪽은 Dict(). 딕셔너리 자료형을 사용하여 아이템을 보관하는 것을 알 수 있습니다.
아이템을 사용하기 위해서는
![image](https://github.com/Sungmo-OSS-Project/txt_game_prototype/assets/25768818/149bad65-fd97-4a58-8760-6dc548a80e6f)
와 같이 ```item_dict["아이템이름"]```을 사용합니다.
장점: 따로 영문으로 아이템 하나하나 참조 변수를 작성할 필요가 없고 딕셔너리에서 아이템의 한글 이름을 가져온다.
단점은 VS Code에서 딕셔너리에 무슨 아이템이 있는지 키와 값이 자동완성이 안 됩니다.

2. 오른쪽은 ```영문 변수명 = 아이템 객체``` 형태로 아이템 객체를 각 변수마다 하나씩 참조하여 목록을 만드는 것을 알 수 있습니다.
아이템을 사용하기 위해서는
![image](https://github.com/Sungmo-OSS-Project/txt_game_prototype/assets/25768818/54bdfb0f-e8c4-435c-b2e4-2b6b52b12068)
와 같이 모듈.아이템이름으로 사용합니다.
장점: VS Code에서 모듈 전체를 가져와서 "모듈."까지만 하면 그 뒤에 어떤 아이템이 있는지 알 수 있고 자동완성이 유용하다.
단점: 아이템 객체를 참조하는 변수가 각각 필요하다.

추가로 파이썬은 한글 변수 또한 지원하고 있으며, 영문 변수로 만들자는 규칙이 정해져 있다면 영문 변수로 진행해야 합니다.

결론: 1번과 2번 중 어떤 방법이 괜찮을지 제안해 주세요.

**Comment by Kei-410** [comment]
저는 2번 방식이 좋다고 생각합니다. 필요에 따라선 한글 변수명 사용도 고려해야겠네요

**Comment by bankingIT** [comment]
저도 2번이 좋은거 같습니다

**Comment by leeyongwooo** [comment]
객체지향.. 객체지향... 2번이 좋은거같습니다

**Comment by rlgh565** [comment]
영어 변수로 하더라도 2번이 좋은 것 같습니다

**Comment by Halozhan** [comment]
2번으로 결정했고, 문제가 해결돼서 닫겠습니다.
