### ISSUE TITLE
전투에 관해 

### ISSUE THREAD

**Issue by rlgh565** [Sungmo-OSS-Project/txt_game_prototype#62]
이벤트를 만들어 보려고 하는데 의논 할게 있어 만듭니다.

소지품의 칼이 있는데 공격력를 만들어 칼이 공격력을 올려주는 건지 칼을 잃는다면 공격을 못하는 건지 무기는 하나만 소유할 수 있는지 같은 것들입니다.

**Comment by Kei-410** [comment]
확률형으로 하지 싶습니다.
좀비와 싸우는 선택지를 고를 경우, 무기가 있다면 100% 전투 승리, 무기 없이 전투 시 50%확률로 승리. 와 같은 느낌으로요.
아니면 [ (나이프 소지 시 해당 선택지 표시) 나이프를 던진다] 와 같은 선택지가 있을 수도 있겠네요.

**Comment by leeyongwooo** [comment]
1학년떄 포켓몬 텍스트로 만들었었는데 그 떈 공격력 N~M하고 상대도 A ~ B 해서 랜덤으로 데미지 입혀서 hp 소진하는 방식으로 했었습니다
