### ISSUE TITLE
좀비 이벤트 등 전투 방식에 관하여

### ISSUE THREAD

**Issue by leeyongwooo** [Sungmo-OSS-Project/txt_game_prototype#65]
좀비 이벤트와 같이 전투가 선택지에 들어가는 경우에 어떻게 해야할지 의논하고싶어 올립니다
1. 플레이어와 좀비 모두 HP가 존재, 랜덤 공격력을 갖고 둘의 HP의 소진시키는 방법 ( 아이템의 존재 유무에따라 랜덤 공격력 값이 달라짐 ) 이 경우 전투 중 "도망간다" 라는 선택지도 존재하며 아이템을 사용하여 전투중에 HP를 올리거나 상대방의 HP를 줄일수도 있음.
 
2. 확률형 승리. 말 그대로 다른 이슈 커밋에서 확인했는데 무기가 있으면 확률이 올라가고 없으면 기본값으로 전투하는 방식

3. 다중 이벤트형 방식. 어찌보면 랜덤형 방식이라 할 수 있는데 이벤트의 방식이 "랜덤형" 이기 때문에 내용은 같게하고 결과 print만 달리 하는 방식 예를들어 이벤트를 zombie_meet_win,  zombie_meet_lose 이런 식으로 다중으로 만들어 해결하는 방법

다른 의견도 생각해보셔서 알려주세요

**Comment by leeyongwooo** [comment]
탐사중 새로운 생존자를 조우하여 전투, 물물교환, 지나가기 등 이런 선택지를 생각하다가 전투방식에 대해 의논하고자 올렸습니다

**Comment by Kei-410** [comment]
확률형, 선택지형 전투 방식으로 진행합니다.
