### ISSUE TITLE
표기법에 관한 이슈

### ISSUE THREAD

**Issue by AsanHO** [Sungmo-OSS-Project/txt_game_prototype#67]
현재 프로젝트에 snake_case와 camelCase가 혼용되어 있습니다.
java의 경우에는 camelCase, python의 경우에는 snake_case를 쓰는 경우가 일반적입니다. 
물론 python에서도 대문자를 쓰는 경우도 있습니다만, 바로 클래스선언입니다.
설계나 동작상에 이슈는 없지만 좀더 프로답게 작업 하는것이 좋을 것 같아 건의 합니다.

**Comment by AsanHO** [comment]
제한 사항으로는 현재로써 모듈간의 의존성이 생각보다 강하기 때문에 변수명들을 바꾸는것은 작업에 충돌이 일어날 수 있기때문에 다소 리스크가 큰 작업 입니다.

**Comment by Kei-410** [comment]
진행하게 될 경우 snake case 로 사용할 것 같습니다.
