### ISSUE TITLE
선택형 이벤트 선택지에 대해서.

### ISSUE THREAD

**Issue by leeyongwooo** [Sungmo-OSS-Project/txt_game_prototype#72]
저번에도 올렸던 내용인데 제 풀리퀘스트중 meet_people를 보면 선택지를 고정으로 만들어서 이벤트를 다량으로 만들어내는게 좋을지 혹은 랜덤기능 등을 채택해 만들지 고민중에 있습니다.
다량으로 만든단 소리는 사람을 만나서 싸워 승리하거나 물물교환을 할 때 예를들면 meet_people_food 이런식으로 해서 물물교환 아이템을 식량중 택1, 승리 전리품도 식량중 택1,
meet_food_battle 에는 전투에 관련된 아이템을 물물교환 및 전리품으로 가져가던지 
아니면 아이템목록에 있는 것중 랜덤으로 가지게 될지 생각해보면 좋겠습니다.
제가 코딩적 지식이 부족해서 아이템 목록에 있는 것들을 랜덤으로 가져오게 하는게  구현이 어떨지 모르겠어서 글 올립니다.

**Comment by Kei-410** [comment]
커밋을 쌓고 참여율을 높이는 것 까지 고려한다면 고정된 아이템 목록을 구성하는 것이 좋다고 봅니다. 
또한 이 경우 이벤트에 다양성을 부여할 수 있다고 봅니다. 
사람을 만나도 그 사람이 어부일 수도 있고, 사냥꾼일 수도 있습니다. 
어부 조우 이벤트, 사냥꾼 조우 이벤트 등 여러 사람을 만나는 이벤트를 만들 수도 있겠네요.

**Comment by kbsam23** [comment]
아이템 목록에서 랜덤으로 선택하는 방식은 다음과 같이 구현할 수 있습니다:

아이템 목록: 게임에서 사용할 수 있는 아이템들을 리스트 형태로 저장합니다. 각 아이템은 고유한 식별자를 가지고 있어야 합니다.

랜덤 선택: 아이템 목록에서 랜덤으로 아이템을 선택하는 로직을 추가합니다. 이를 위해 프로그래밍 언어나 게임 개발 도구에서 제공하는 난수(Random) 함수를 사용할 수 있습니다.

선택된 아이템 활용: 선택된 랜덤 아이템을 이벤트에서 활용합니다. 예를 들어, 만난 사람과 싸움을 할 때 선택된 랜덤 아이템을 전리품으로 가져가거나 물물교환에 사용할 수 있습니다.
