### ISSUE TITLE
혈청 아이템 무게에 관하여.

### ISSUE THREAD

**Issue by leeyongwooo** [Sungmo-OSS-Project/txt_game_prototype#74]
사람을 만나는 이벤트나 좀비를 만나 해치우는 이벤트 내에서 혈청을 획득 할 때,
이 혈청을 가지고 복귀하는 디메리트를 만들고 싶어 무게를 우선 3으로 책정했습니다.
아무래도 엔딩과 관련된 아이템이기 때문에 이를 챙기기 위해선 어느정도 위험을 부담해야 한다고 생각했는데 여려분의 생각은 어떨지
남겨주시면 참고하겠습니다.

혹은 혈청의 무게를 완전 0으로 만들어 무게 상관 없이 들고다닐 수 있게 하는 방법도 생각은 해봤는데 뭐가 더 나을지 모르겠습니다.

**Comment by Halozhan** [comment]
맞습니다. 들고다니는걸 감수하기 위해 무게를 가지는게 좋다고 생각합니다.

**Comment by Kei-410** [comment]
저도 혈청은 무게를 조금 높게 설정하는 것이 좋다고 생각합니다. 혈청을 얻는 것 자체가 엔딩에 직결되는 만큼 상응하는 리스크가 있어야한다고 생각합니다.

**Comment by rlgh565** [comment]
이건 엔딩이 어떻게 되냐에 따라 다를 것 같습니다. 만약 일정 day에 따라 쉘터 복귀를 하고 혈청을 일정 갯수 모아야 한다면 리스크가 되지만 혈청을 모으고 곧바로 엔딩으로 가는지 혈청을 하나만 모아도 되는지 논의가 필요합니다.
즉
1. 혈정의 갯수 
2. 엔딩의 구조 

에 의견을 써주세요

**Comment by Kei-410** [comment]
이에 대한 논의는 새로운 이슈를 오픈하겠습니다.
