### ISSUE TITLE
게임의 기본 진행 구조

### ISSUE THREAD

**Issue by Kei-410** [Sungmo-OSS-Project/txt_game_prototype#8]
1. 기초 정비
쉘터 출발 이전에 아이템을 소지할 수 있다.

2. 탐사 출발
쉘터에서 출발하며 각종 이벤트에 노출된다.

3. 이벤트
물자 획득 이벤트, 물자 손실 이벤트, 체력 증감 이벤트, 상태 추가 및 제거 이벤트, 물자 교환 이벤트, 전투 이벤트 등의 각종 이벤트가 발생한다.

4. 쉘터 복귀
플레이어는 특정 시점마다 '쉘터 복귀' 선택지를 선택하여 쉘터로 복귀할 수 있다.

5. 정비
체력이 최대치까지 회복되며, 자신이 소지한 아이템을 저장, 판매, 폐기할 수 있다.
플레이어가 모든 정비를 마친 경우 다시 '탐사 출발'을 선택하여 2 ~ 5의 과정을 반복한다.

**Comment by leeyongwooo** [comment]
1. 기초정비, 2.탐사출발 에서는 가방의 max무게, 혹은 중요도를 파악하여 일정 아이템만을 가져갈 수 있는게 좋을 거 같습니다.
3. 이벤트 중에서도 역시 동일하게 max무게, 중요도를 넘어선다면 현재 가진 아이템을 버리고 가져가던지 새로 얻은 아이템을 포기하는 방식으로 진행하면 좋을 거 같습니다. 물론 획득 아이템 중에는 "더 좋은 가방"도 있을 수 있을 거 같습니다.

**Comment by rlgh565** [comment]
**기초 정비**
기초 정비는 초기 장비를 가지는 것으로 이해를 했습니다. 그렇다면 초반 물품과 플레이어의 스테이더스가 어떻게 되는지 구상해야 합니다. 메인 코딩으로 채택했던 조홍인님의 구상은 체력,버프,인벤토리,무게 등이 있습니다. 인벤토리와 무게에 대해서는 논의가 필요할 것 같지만 인벤토리는 단순히 아이템의 공간이라고 생각했고 무게는 아이템의 제한을 두는 기능이라고 생각했습니다. 그렇다면 초기에 어떤 물품을 가져가는지 어떤 버프를 가져가는지 생각해야 합니다. 체력은 20이로 되어 있고 제가 생각하는 방법으로는 물품으로 나중에 체력을 회복할 수 있도록 빵 한개, 버프는 이벤트로 상호작용하는 게 좋을 듯합니다. 
기초 정비 
빵 한개 

**탐사 출발**
이벤트 발생

**쉘터 복귀**
어떤 주기에 쉘터 복귀를 할 수 있는지 정해야 합니다. 이벤트가 발생 할때 마다 쉘터 복귀를 해도 좋습니다. 제가 생각한 방법으로 3번정도 이벤트를 진행한 뒤 쉘터 복귀를 하는 게 좋을 것 같습니다.

**정비**
체력을 모두 회복하거나 아이템을 정비합니다. 

여기서 정해야 할 것은 어느 시점에 엔딩을 할 것인지 입니다. 이벤트를 20번 정도 진행한 다음 엔딩을 본다고 하면 쉘터로 복귀한 뒤 엔딩이 나는 지,도중에 나는 지 스토리 구상이 필요하고 기초 정비도 제가 생각한 방법이고 버프가 무슨 종류가 있는지나 쉘터 복귀나 정비 같은 부분에서도 다른 방식을 원할 수도 있습니다. 정리해서 논의가 필요한 부분은 

1. 기초 정비 목록
2. 버프 유형이나 무게 제한,인벤토리 횟수 
3. 쉘터 복귀 주기 
4. 정비 진행 내용

으로 4가지가 있고 다른 분들은 4가지에 대해서나 다른 의견이 필요한 부분 말씀해주세요
