### ISSUE TITLE
플레이어 스테이터스 설명

### ISSUE THREAD

**Issue by Kei-410** [Sungmo-OSS-Project/txt_game_prototype#9]
체력(health, health_max)
기본(시작)값은 20으로 고정.
체력이 0이 되는 경우 플레이어는 사망하며, 게임 오버.
최대체력(health_max)이 존재하며, 체력 값은 최대체력보다 커질 수 없음.
특정 이벤트를 통하여 체력과 최대 체력에 증감이 있을 수 있음.

상태(buffs)
딕셔너리의 형태로 {상태명: 상태레벨(int)} 로 구성된다. 
게임 진행에 있어 플레이어의 선택지를 늘려주거나, 플레이어의 행동을 제약시킬 수 있다.
상태는 특정 이벤트를 통해 새로운 상태가 추가되거나, 기존 상태레벨에 증감이 있을 수 있다. 

아이템(items)
긍정적 상태처럼 특정 선택지를 선택할 수 있다.
하지만 아이템 중 일회성 아이템의 경우, 해당 아이템 사용 시 소멸한다.

무게(weight, weight_limit)
아이템마다 무게가 다르며, 플레이어가 한 번에 소지할 수 있는 아이템 수량에 제한을 두는 기능이다.
플레이어는 시작 시 최대무게(weight_limi)가 설정된다.
특정 이벤트를 통하여 최대 무게를 늘릴 수 있다.

**Comment by Halozhan** [comment]
체력은 current_health 대신 health로 하는게 어떨까요?
긍정적 상태와 부정적 상태는 +와 -의 부호를 사용하여 레벨을 나타냄으로써 buffs라는 dict형 변수 하나로 정의하는게 좋아보여요!
아이템은 맞춤법 검사기에서는 1회성 대신 일회성으로 표현하는게 적합하다고 했습니다.
최대 무게는 weight_limit대신 weight_max로 사용해도 괜찮다고 생각해요!

**Comment by Kei-410** [comment]
말씀하신 내용들 반영하여 메인 브랜치, 상기 공지 모두 수정했습니다.
